function imgout=reduced(img)


% weighted function generated by kernel

windowf=[1 4 6 4 1;
        4 16 24 16 4;
        6 24 36 24 6;
        4 16 24 16 4;
        1 4 6 4 1];
    
kernel=windowf/256;    
    
    
img = im2double(img);
[r c d]= size(img);
imgout = [];

for l = 1:d
	img1 = img(:,:,l);
	Filtered = imfilter(img1,kernel);
	imgout(:,:,l) =Filtered(1:2:r,1:2:c);
end



end
